modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
modId="arcaneadditions"
version="${file.jarVersion}"
displayName="Arcane Additions"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="arcaneadditions.png" #optional
# A text field displayed in the mod UI
#credits="" #optional
authors="nivthefox, anomalagous"
description='''
A wealth of new magical mysteries for the Mana and Artifice mod.
'''
[[dependencies.arcaneadditions]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.arcaneadditions]]
    modId="bmorph"
    mandatory=true
    versionRange="[1.18.1-2.0.1,1.18.1-3.0.0)"
    ordering="NONE"
    sides="BOTH"
[[dependencies.arcaneadditions]]
    modId="mna"
    mandatory=true
    versionRange="[1.7,1.8)"
    ordering="NONE"
    sides="BOTH"