modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GPLv3"

[[mods]] #mandatory
modId="arcaneadditions"
version="${file.jarVersion}"
displayName="Arcane Additions"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="arcane-additions.png" #optional
# A text field displayed in the mod UI
credits="Thanks to Joefoxe of Hexerei for inspiring me to start modding, and to Mithion for making my minecraft experience magical.  Thanks to NotNova for their incredible pixel art and to Aranai for models and textures."
authors="nivthefox, anomalagous"
description='''
A wealth of new magical mysteries for the Mana and Artifice mod.'''

[[dependencies.arcaneadditions]]
    modId="forge"
    mandatory=true
    versionRange="[43.3.5,44)"
    ordering="NONE"
    side="BOTH"
[[dependencies.arcaneadditions]]
    modId="mna"
    mandatory=true
    versionRange="[2.1,3)"
    ordering="NONE"
    sides="BOTH"